<div class="container" data-bind="scope: 'api'">
    <div class="button-container">
        <button class="postUser" data-bind="click: clickedPostUser">
            <?= __('POST request for user') ?>
        </button>
        <button class="getUser" data-bind="click: clickedGetUser">
            <?= __('GET request for user') ?>
        </button>
        <button class="getProducts" data-bind="click: clickedGetProducts">
            <?= __('GET request for products list') ?>
        </button>
    </div>
    <div class="form-container">
        <form class="form">
            <label class="content-id"><?= __('Enter user ID') ?>:
                <input type="text" class="user-id">
            </label>
            <label class="content-weathertype"><?= __('Enter WeatherType Name') ?>:
                <select class="weathertype-id">
                    <?php foreach($block->getWeatherTypes() as $weatherId => $weatherName): ?>
                        <option value="<?= $block->escapeHtml($weatherId) ?>"><?= $block->escapeHtml($weatherName) ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
        </form>
        <button class="submit-data" data-bind="click: clickedSubmitButton"><?= __('Submit') ?></button>
        <span class="output" data-bind="text: outputData"></span>
    </div>
</div>
<script type="text/x-magento-init">
     {
        ".container": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "api": {
                        "component": "AdeoWeb_WeatherApplication/js/api",
                        "url": "<?= $block->escapeJs($block->getUrl()) ?>"
                    }
                }
            }
        }
     }
</script>
